version: 2

project_name: bench-exporter

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: bench-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - formats: [tar.gz]

checksum:
  name_template: 'checksums.txt'

blobs:
  - directory: dist

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers_v2:
  - id: bench-exporter
    ids:
      - bench-exporter
    tags:
      - "{{ .Version }}"
      - latest
    images:
      - "{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .Env.GITHUB_REPOSITORY }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    platforms:
      - linux/amd64
    sbom: false
    flags:
    - "--provenance=false"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
